version: '2'
services:
    backend:
        build:
            context: ./
            dockerfile: ./backend/docker/Dockerfile
        ports:
            - "5000:5000"
        volumes:
            - ./backend:/app/backend
        environment:
            FLASK_APP: server.py
            FLASK_DEBUG: 1
            LC_ALL: C.UTF-8
            LANG: C.UTF-8
            ENV: DEV
        entrypoint: flask run --host=0.0.0.0
        user: "${UID}:${GID}"
    frontend:
        build:
            context: ./markov-web
            dockerfile: ./docker/Dockerfile
        ports:
            - "8080:8080"
        volumes:
            - ./markov-web:/app
        entrypoint: /app/docker/entrypoint-run.sh
        user: "${UID}:${GID}"
