FROM python:3.9

WORKDIR /app

COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend .

ENTRYPOINT ["gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "server:app"]
